### ISSUE TITLE
注册页面的验证码判断有BUG

### ISSUE THREAD

**Issue by tmkddskf** [lifei6671/SmartWiki#17]
描述：
    在没有开启验证码的时候，注册页面将会无法注册。
修复方法：
    将register.blade.php中的
    else if(code !== undefined && code === ""){
                    $("#code").focus().tooltip({title : '验证码不能为空',trigger : 'manual'})
                        .tooltip('show')
                        .parents('.form-group').addClass('has-error');
                    return false;
                }
   改为
   else if(**$("#code").length > 0** && code !== undefined && code === ""){
                    $("#code").focus().tooltip({title : '验证码不能为空',trigger : 'manual'})
                        .tooltip('show')
                        .parents('.form-group').addClass('has-error');
                    return false;
                }

**Comment by lifei6671** [comment]
确实是个BUG。
