### ISSUE TITLE
普通模板markdown ##字符后未添加空格

### ISSUE THREAD

**Issue by aizaimenghuangu** [lifei6671/SmartWiki#25]
操作步骤：
1、在文档编辑中添加模板，选择普通模板
2、查看模板中的markdown字符

结果：
##SmartWiki是什么?
其中 ##后面未添加空格，导致保存的内容未非markdown文档

**Comment by lifei6671** [comment]
嗯嗯，这个问题已经发现了，新版本修复，感谢反馈。

**Comment by lifei6671** [comment]
新版本已修复。
