### ISSUE TITLE
编辑文档时文档加载失败 

### ISSUE THREAD

**Issue by sir051223** [lifei6671/SmartWiki#37]
基于centos系统部署  其他访问都没有问题  

编辑文档时文档弹出“加载失败”

**Comment by lifei6671** [comment]
您可以尝试看下日志看看具体是什么错误。日志在storage/logs里面。

**Comment by sir051223** [comment]
storage/logs里面没有日志   storage以及其下文件夹是777权限

**Comment by lifei6671** [comment]
您用Chrome浏览器打开，按f12调出开发者工具，看下编辑文档时请求返回是什么内容？

**Comment by sir051223** [comment]
查看了返回的内容，怀疑是数据库字符集的问题，对了，数据库字符集有要求吗

**Comment by sir051223** [comment]
找到问题了，是nginx服务器的问题，我的服务器环境是nginx+apache  直接访问apache没有问题  nginx反向代理处理出现了问题，谢谢哈
